# Generated by Django 4.2 on 2025-10-05 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanzasImpresoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanza_id', models.CharField(blank=True, max_length=50, null=True)),
                ('impresora_ip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CierresDiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('zona_vive', models.CharField(max_length=50)),
                ('credito', models.IntegerField(default=0)),
                ('credito_maximo', models.IntegerField(default=0)),
                ('credito_plazo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.IntegerField(blank=True, null=True)),
                ('monto_credito', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('plazo_credito', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('abonado', models.FloatField(blank=True, null=True)),
                ('cliente_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=10)),
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(max_length=20)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cajero', models.CharField(max_length=100)),
                ('pedido_id', models.IntegerField()),
                ('verificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosBalanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('producto', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('producto', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.FloatField(blank=True, default='', null=True)),
                ('unidad', models.CharField(choices=[('U', 'U'), ('K', 'K')], max_length=20)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('BS', 'BS')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('barcode', models.CharField(blank=True, max_length=200, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('precio_detal', models.FloatField()),
                ('precio_mayor', models.FloatField(blank=True, null=True)),
                ('precio_especial', models.FloatField(blank=True, null=True)),
                ('subproducto', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('relacion_subproducto', models.IntegerField(blank=True, default=0, null=True)),
                ('categoria', models.ManyToManyField(to='pos.categoriasproductos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_total', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('pagado_fecha', models.DateTimeField(blank=True, null=True)),
                ('despachado_fecha', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.IntegerField(default=0)),
                ('dolar_al_pagar', models.FloatField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=400, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('pesador', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_pedido_balanza', models.IntegerField(blank=True, null=True)),
                ('productos', models.ManyToManyField(to='pos.productospedido')),
            ],
        ),
        migrations.CreateModel(
            name='estadoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('dineroInicio', models.JSONField(blank=True, null=True)),
                ('dineroFinal', models.JSONField(blank=True, null=True)),
                ('dineroEsperado', models.JSONField(blank=True, null=True)),
                ('pedidos_pendientes', models.JSONField(blank=True, help_text="Pedidos en estado 'Por Pagar' al momento del cierre", null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditoAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito_id', models.IntegerField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_neto', models.FloatField(blank=True, null=True)),
                ('denominaciones', models.JSONField(blank=True, null=True)),
                ('vuelto', models.JSONField(blank=True, null=True)),
                ('cierre_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonos_creditos', to='pos.estadocaja')),
            ],
        ),
    ]
