# Generated by Django 4.1.7 on 2025-09-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_pesador', models.CharField(help_text='Username del pesador que tiene este pedido activo', max_length=50, unique=True)),
                ('pedido_json', models.JSONField(help_text='Array de productos en el formato del frontend: [{id, nombre, cantidad, precio, ...}]')),
                ('precio_total', models.FloatField(default=0.0, help_text='Precio total del pedido en USD')),
                ('cliente_id', models.IntegerField(default=0, help_text='ID del cliente asignado al pedido (0 = cliente genérico)')),
                ('cliente_nombre', models.CharField(default='Cliente', help_text='Nombre del cliente para mostrar en UI', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del pedido activo')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación')),
                ('estacion_actual', models.CharField(blank=True, help_text='Identificador de la estación donde se está trabajando actualmente', max_length=100, null=True)),
                ('numero_productos', models.IntegerField(default=0, help_text='Número total de productos en el pedido (para consultas rápidas)')),
            ],
            options={
                'verbose_name': 'Pedido Activo',
                'verbose_name_plural': 'Pedidos Activos',
                'ordering': ['-fecha_ultima_modificacion'],
            },
        ),
    ]
