# Generated by Django 4.2 on 2025-10-08 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0002_alter_producto_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('traslado', 'Traslado'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la ubicación', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('bodega', 'Bodega'), ('punto_venta', 'Punto de Venta')], help_text='Tipo de ubicación', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='¿Está activa la ubicación?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(help_text='Número de orden único', max_length=50, unique=True)),
                ('fecha_orden', models.DateField(help_text='Fecha de creación de la orden')),
                ('fecha_esperada', models.DateField(blank=True, help_text='Fecha esperada de entrega', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('recibida_parcial', 'Recibida Parcial'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('total', models.FloatField(default=0, help_text='Total de la orden')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='pos.proveedor')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='Cantidad movida (siempre positiva)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, help_text='Referencia al pedido, orden de compra u otro documento', max_length=100, null=True)),
                ('costo_unitario', models.FloatField(default=0, help_text='Costo unitario en el momento del movimiento')),
                ('notas', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='pos.producto')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.tipomovimiento')),
                ('ubicacion_destino', models.ForeignKey(blank=True, help_text='Ubicación de destino (para entradas y traslados)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='pos.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(blank=True, help_text='Ubicación de origen (para salidas y traslados)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='pos.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InventarioUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.FloatField(default=0, help_text='Cantidad actual en stock')),
                ('costo_promedio', models.FloatField(default=0, help_text='Costo promedio ponderado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='pos.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='pos.ubicacion')),
            ],
            options={
                'verbose_name': 'Inventario por Ubicación',
                'verbose_name_plural': 'Inventarios por Ubicación',
                'ordering': ['ubicacion', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ordenada', models.FloatField(help_text='Cantidad ordenada')),
                ('cantidad_recibida', models.FloatField(default=0, help_text='Cantidad recibida')),
                ('costo_unitario', models.FloatField(help_text='Costo unitario del producto')),
                ('subtotal', models.FloatField(help_text='Subtotal (cantidad_ordenada * costo_unitario)')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Órdenes de Compra',
            },
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['-fecha'], name='pos_movimie_fecha_558783_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', '-fecha'], name='pos_movimie_product_2fee16_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento', '-fecha'], name='pos_movimie_tipo_mo_8ebb47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioubicacion',
            unique_together={('producto', 'ubicacion')},
        ),
        migrations.AlterUniqueTogether(
            name='detalleordencompra',
            unique_together={('orden_compra', 'producto')},
        ),
    ]
