# Generated by Django 4.2 on 2025-10-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_proveedor_tipomovimiento_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventarioubicacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventarioubicacion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='inventarioubicacion',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='ubicacion_destino',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='ubicacion_origen',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='usuario_creador',
        ),
        migrations.DeleteModel(
            name='DetalleOrdenCompra',
        ),
        migrations.DeleteModel(
            name='InventarioUbicacion',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='TipoMovimiento',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
